### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by aphelionz** [ipfs-rust/logo#1]
This issue stands to track the design work of the Rust IPFS logo from design to ideation.

The elements we'd like to combine are:

- Hexagonal shape (for stickers and visual cohesion)
- Similarity to go-ipfs and js-ipfs logos
- The  Rust Logo 
![image](https://user-images.githubusercontent.com/106148/75078429-92720500-54d3-11ea-9c49-255b1292d6d6.png)
- The IPFS Cube motif
- A crab for "rustaceans" (optional)

Some ideas that have been proposed are below:

![Screenshot_20200220-123433](https://user-images.githubusercontent.com/106148/75078320-50e15a00-54d3-11ea-9df4-43d6d04466cf.png)

![image](https://user-images.githubusercontent.com/106148/75078408-84bc7f80-54d3-11ea-8855-c5ed23d6e617.png)

**Comment by aphelionz** [comment]
Personally I like the crab, and I really like the js-ipfs logo's treatment of the cube, namely the cube within a cube.

![image](https://user-images.githubusercontent.com/106148/75078523-cd743880-54d3-11ea-86ec-dfa154fac4b1.png)

**Comment by momack2** [comment]
Some hacky mocks using the rust logo:
![image](https://user-images.githubusercontent.com/618519/75190567-6ccc4200-5705-11ea-8cb3-61e80faea208.png)
![image](https://user-images.githubusercontent.com/618519/75190584-75247d00-5705-11ea-8f32-d6f3ac9efd79.png)

**Comment by alanshaw** [comment]
FWIW the JS logo works well when integrated as a panel on the IPFS cube because it is a square already. Looking at the mockups, IMHO, the rust logo in that same panel won’t be as effective. I think we should also consider if we do _really_ want to establish “logo in panel of the cube” as a convention for other implementations!

I _really_ like the crab holding up the IPFS logo above and I like the idea of each impl having it’s own identity...That said, I do agree that we should probably look to incorporate the rust logo rather than the crab for easier brand recognition.

**Comment by aphelionz** [comment]
I like the crab too. It seems the convention in the Rust community is that the R-within-a-gear is the official logo and the crab is a mascot.

It's easy for Equilibrium to create more fun + cute illustrations like that one with the crab character helping, being helped by, or just palling around with the IPFS cube in various ways. We could put those in blog posts, for example. They won't be "official," just entertaining.

For the logo - honestly, our main driver is that it's PL-approved and that you feel that it's at least cohesive with the other logos. Happy to follow your lead there :+1:

**Comment by alanshaw** [comment]
I had a vision

<img src="https://user-images.githubusercontent.com/152863/75291051-63cc9500-5819-11ea-9c56-c96c04249283.png" width="250" />
<img src="https://user-images.githubusercontent.com/152863/75291055-65965880-5819-11ea-86d0-97f6a57f5264.png" width="250" />
<img src="https://user-images.githubusercontent.com/152863/75291059-66c78580-5819-11ea-9b00-7a7e624aadf2.png" width="250" />

**Comment by aphelionz** [comment]
Confession: I'm making myself laugh imagining the crab and the cube in a "Calvin and Hobbes"-esque dancing montage

![image](https://user-images.githubusercontent.com/106148/75291333-fe17e300-57ef-11ea-9364-378b6015b716.png)

![image](https://user-images.githubusercontent.com/106148/75291381-125be000-57f0-11ea-88af-449ed59e87a1.png)

**Comment by aphelionz** [comment]
I like your vision @alanshaw

**Comment by momack2** [comment]
OOOHH! I love this one: 
![image](https://user-images.githubusercontent.com/618519/75293642-7031fd00-57db-11ea-9cb7-60a5d51a3651.png)

@ericronne might 🤯given another crazy iteration of our brand presence though...

**Comment by ericronne** [comment]
That version looks cool. A slightly lighter tint for the R fill — somewhere between the top and middle versions (in the neighborhood of #79cdd4?) — should increase contrast/legibility without making the R feel too disconnected from the cube.

**Comment by alanshaw** [comment]
@ericronne done - `#79cdd4` looks good to me.

Here's the pack with some sizes and an SVG version: https://ipfs.io/ipfs/QmRcFsCvTgGrB52UGpp9P2bSDmnYNTAATdRf4NBj8SKf77

<img src="https://ipfs.io/ipfs/QmRcFsCvTgGrB52UGpp9P2bSDmnYNTAATdRf4NBj8SKf77/rust-ipfs-logo-1024w.png" width="512" />

**Comment by alanshaw** [comment]
https://github.com/ipfs-rust/rust-ipfs/pull/55

Will someone please update the github org logo? 🙏

**Comment by aphelionz** [comment]
@alanshaw Done!

@momack2 @ericronne To close out this issue, do we all agree that:

1. This will be the **official** Rust IPFS logo until PL says otherwise, to be used at the front of all Rust IPFS-related things like the GitHub, OpenCollective, etc
2. Equilibrium and the Rust IPFS community can use the Crab + Cube motif in other non-official capacities like blog posts, videos, etc. So long as the relationship between the crab and the cube is cordial and helpful?

**Comment by ericronne** [comment]
Boom! I also recommend that we generate a monochrome (black) version.

**Comment by vmx** [comment]
Has anyone checked if we are allowed to use the Rust logo? After a quick search I found https://github.com/rust-lang/rust/issues/11562 which mentions https://www.mozilla.org/en-US/foundation/trademarks/policy/ which I then haven't read :)

**Comment by aphelionz** [comment]
@vmx Yes, we checked. See https://www.rust-lang.org/policies/media-guide

> The Rust and Cargo logos (bitmap and vector) are owned by Mozilla and distributed under the terms of the Creative Commons Attribution license (CC-BY). This is the most permissive Creative Commons license, and allows reuse and modifications for any purpose. 

**Edit:** There's also the Trademark clause too, which doesn't apply to us since Rust IPFS is not a "commercial" endeavor.

**Comment by aphelionz** [comment]
In the README section of each repo we should attribute and link to the CC license properly, otherwise I think we're good

**Comment by momack2** [comment]
@aphelionz agree this should be the logo until the community comes up with something better. Def feel free to use the crab (he's so cute!) just ideally not in a way that creates confusion about what the logo is ;)

**Comment by aphelionz** [comment]
Awesome!
